plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  
title: Capipocavara
since: 2020
author: Elscherino

url: https://www.capipocavara.de
baseurl: ""
description: >-
  Virtual Reality Development, Unity, Capybaras!

permalink: /:slug

theme_config:
  appearance: dark
  appearance_toggle: true
  date_format: "%Y-%m-%d" # customize how date is formatted

  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  show_post_nav: true # show prev/next links on posts
  show_toc: true # allow per-post table of contents via toc: true front matter
  # options for "home" page
  home:
    title_projects: Projects
    title_blog: Devlog

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false