plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  
title: Capipocavara
since: 2020
author: Elscherino

url: https://www.capipocavara.de
baseurl: ""
description: >-
  Virtual Reality Development, Unity, C#/.NET, Capybaras!

permalink: /:slug

theme_config:
  appearance: dark
  appearance_toggle: true
  date_format: "%Y-%m-%d"

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, .jekyll-cache, CNAME, LICENSE]